/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentoacademico;

import javax.swing.JOptionPane;

/**
 *
 * @author joao-
 */
public class CalculaNota extends javax.swing.JFrame {

    /**
     * Creates new form CalculaNota
     */
    public CalculaNota() {
        initComponents();
    }

    private void gerenciamento() {

        double nota1 = 0, nota2, nota3, total = 0;
        double primeira = 0, segunda = 0, terceira = 0;
        int primeiranotacorreta = 0, segundanotacorreta = 0, terceiranotacorreta = 0;
        
        //TRATANDO ERROS DO USUARIO I
        //Verifica se existem campos vazios, em caso afirmativo, exibe uma mensagem de erro
        if (primeiraetapa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo da primeira etapa está vazio , favor preenchê - lo",
                    "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        }

        if (segundaetapa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo da segunda etapa está vazio , favor preenchê - lo",
                    "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        }

        if (terceiraetapa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo da terceira etapa está vazio , favor preenchê - lo",
                    "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        }
        
        //Armazena os valores informados pelo usuario em variavel
        nota1 = Double.valueOf(primeiraetapa.getText());
        nota2 = Double.valueOf(segundaetapa.getText());
        nota3 = Double.valueOf(terceiraetapa.getText());

        //TRATANDO ERROS DO USUARIO II
        /*Se a nota informada estiver dentro do aceitado pelo Centro Universitario, armazena o valor
        em variavel. Senao, exibe uma mensagem de erro.*/
        if (nota1 >= 0 && nota1 <= 30) {
            primeira = nota1;
            primeiranotacorreta = 1;
        } else {
            JOptionPane.showMessageDialog(null, "A informação da nota da primeira etapa não é válida! Favor "
                    + "informar um número entre 0 e 30",
                    "Informação Inválida Nota Primeira Etapa", JOptionPane.WARNING_MESSAGE);
        }

        if (nota2 >= 0 && nota2 <= 30) {
            segunda = nota2;
            segundanotacorreta = 1;
        } else {
            JOptionPane.showMessageDialog(null, "A informação da nota da segunda etapa não é válida! Favor informar um número entre 0 e 30",
                    "Informação Inválida Nota Segunda Etapa", JOptionPane.WARNING_MESSAGE);
        }

        if (nota3 >= 0 && nota3 <= 40) {
            terceira = nota3;
            terceiranotacorreta = 1;
        } else {
            JOptionPane.showMessageDialog(null, "A informação da nota da terceira etapa não é válida!"
                    + " Favor informar um número entre 0 e 30",
                    "Informação Inválida Nota Terceira Etapa", JOptionPane.WARNING_MESSAGE);
        }
        
        /*Apos todos os valores informados e armazenados, faz o calculo e exibe o valor
        final junto de uma mensagem baseada na nota obtida.*/
        if (primeiranotacorreta == 1 && segundanotacorreta == 1 && terceiranotacorreta == 1) {
            total = primeira + segunda + terceira;
            totalnotas.setText(String.valueOf(total));

            if (total >= 60 && total <= 100) {
                JOptionPane.showMessageDialog(null, "O aluno foi aprovado na disciplina!"
                        + "\n" + "PARABÉNS!!!", "APROVADO!!!",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            if (total >= 20 && total <= 59) {
                JOptionPane.showMessageDialog(null, "O aluno está de suplementar na disciplina! =/"
                        + "\n" + "Estude para passar, beleza?!", "SUPLEMENTAR =/",
                        JOptionPane.WARNING_MESSAGE);
            }

            if (total >= 0 && total <= 19) {
                JOptionPane.showMessageDialog(null, "O aluno foi reprovado na disciplina"
                        + "\n"
                        + "Só ano que vem amigo... quem mandou não estudar né?!", "REPROVADO =(",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    //Limpa os campos preenchidos pelo usuario e com resultado do calculo
    private void limpar() {
        primeiraetapa.setText("");
        segundaetapa.setText("");
        terceiraetapa.setText("");
        totalnotas.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        primeiraetapa = new javax.swing.JTextField();
        segundaetapa = new javax.swing.JTextField();
        terceiraetapa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalnotas = new javax.swing.JTextField();
        calcular = new javax.swing.JToggleButton();
        limpar = new javax.swing.JToggleButton();
        totalnotas1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notas Acadêmicas");

        jLabel6.setText("Primeira Etapa (0 a 30pts):");

        jLabel7.setText("Segunda Etapa (0 a 30pts):");

        jLabel8.setText("Terceira Etapa (0 a 40pts):");

        primeiraetapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiraetapaActionPerformed(evt);
            }
        });

        segundaetapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundaetapaActionPerformed(evt);
            }
        });

        terceiraetapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceiraetapaActionPerformed(evt);
            }
        });

        jLabel9.setText("Resultado Final:");

        totalnotas.setEditable(false);
        totalnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalnotasActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        totalnotas1.setEditable(false);
        totalnotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalnotas1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Situação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalnotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primeiraetapa)
                                    .addComponent(segundaetapa)
                                    .addComponent(terceiraetapa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(primeiraetapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(segundaetapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(terceiraetapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalnotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalnotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void primeiraetapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiraetapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeiraetapaActionPerformed

    private void segundaetapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundaetapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundaetapaActionPerformed

    private void terceiraetapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceiraetapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terceiraetapaActionPerformed

    private void totalnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalnotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalnotasActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:

        gerenciamento();
    }//GEN-LAST:event_calcularActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:

        limpar();
    }//GEN-LAST:event_limparActionPerformed

    private void totalnotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalnotas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalnotas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculaNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculaNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculaNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculaNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculaNota().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton calcular;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton limpar;
    private javax.swing.JTextField primeiraetapa;
    private javax.swing.JTextField segundaetapa;
    private javax.swing.JTextField terceiraetapa;
    private javax.swing.JTextField totalnotas;
    private javax.swing.JTextField totalnotas1;
    // End of variables declaration//GEN-END:variables
}
