/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentoacademico;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joao-
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); //Faz a janela abrir em tela cheia
    }

    //Funcao para iniciar o cadastro de dados
    public void iniciaAplicacao() {
        Interface exibeInterface = new Interface();
        exibeInterface.setVisible(true);
    }

    //Funcao para exibir caixa de mensagem confirmando o fechamento da aplicacao
    public void fechaAplicacao() {
        switch (JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Você está fechando a aplicação...",
                JOptionPane.YES_NO_OPTION)) {
            case 0:
                System.exit(0);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        submenuCadastrar = new javax.swing.JMenuItem();
        submenuSair = new javax.swing.JMenuItem();
        menuInformacao = new javax.swing.JMenu();
        submeuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento Acadêmico");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+6f));
        jLabel3.setText("DESENVOLVIDO POR IGOR, JOÃO, MATHEUS E TULIO");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+36f));
        jLabel4.setText("GERENCIAMENTO ACADÊMICO");

        jLabel1.setText("Para iniciar a aplicação, basta clicar no botão abaixo:");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar Aplicação");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel2.setText("Atividade Discente Autonôma de POOE I");

        jLabel5.setText("Versão 0.0.1");

        menuCadastro.setText("Cadastro");

        submenuCadastrar.setText("Cadastrar Aluno");
        submenuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCadastrarActionPerformed(evt);
            }
        });
        menuCadastro.add(submenuCadastrar);

        submenuSair.setText("Sair");
        submenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSairActionPerformed(evt);
            }
        });
        menuCadastro.add(submenuSair);

        jMenuBar1.add(menuCadastro);

        menuInformacao.setText("Informações");
        menuInformacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInformacaoMouseClicked(evt);
            }
        });
        menuInformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformacaoActionPerformed(evt);
            }
        });

        submeuSobre.setText("Sobre");
        submeuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeuSobreActionPerformed(evt);
            }
        });
        menuInformacao.add(submeuSobre);

        jMenuBar1.add(menuInformacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(195, 195, 195)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCadastrarActionPerformed
        iniciaAplicacao();
    }//GEN-LAST:event_submenuCadastrarActionPerformed

    private void submenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSairActionPerformed
        fechaAplicacao();
    }//GEN-LAST:event_submenuSairActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciaAplicacao();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        fechaAplicacao();
    }//GEN-LAST:event_btnSairActionPerformed

    private void menuInformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformacaoActionPerformed

    }//GEN-LAST:event_menuInformacaoActionPerformed

    private void menuInformacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInformacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInformacaoMouseClicked
    //Submenu com credito para os desenvolvedores
    private void submeuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "ADA de Programação Orientada a Objetos I"
                + "\n" + "\n" + "Desenvolvido por " + "\n"
                + "- Igor Silva" + "\n"
                + "- João Paulo Silva" + "\n"
                + "- Matheus Barcelos" + "\n"
                + "- Tulio Souza" + "\n", "Gerenciamento Acadêmico ©",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_submeuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuInformacao;
    private javax.swing.JMenuItem submenuCadastrar;
    private javax.swing.JMenuItem submenuSair;
    private javax.swing.JMenuItem submeuSobre;
    // End of variables declaration//GEN-END:variables
}
